- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: kubectl delete -f /home/ubuntu/test/Deployment.yml -n default
     - name: delete old service
       command: kubectl delete -f /home/ubuntu/test/Service.yml -n default
     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/test/Deployment.yml -n default
     - name: create new service
       command: kubectl apply -f /home/ubuntu/test/Service.yml -n default
